"""empty message

Revision ID: ed173df4e879
Revises: 
Create Date: 2023-08-07 07:08:49.708961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed173df4e879'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('site', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_description'), 'sources', ['description'], unique=False)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_site'), 'sources', ['site'], unique=True)
    op.create_index(op.f('ix_sources_source'), 'sources', ['source'], unique=False)
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawled_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Y', 'N'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_crawled_at'), 'urls', ['crawled_at'], unique=False)
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
    op.create_index(op.f('ix_urls_source_id'), 'urls', ['source_id'], unique=False)
    op.create_index(op.f('ix_urls_status'), 'urls', ['status'], unique=False)
    op.create_index(op.f('ix_urls_url'), 'urls', ['url'], unique=True)
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawled_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=500), nullable=True),
    sa.Column('author', sa.VARCHAR(length=500), nullable=True),
    sa.Column('posted_at', sa.VARCHAR(length=150), nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_author'), 'contents', ['author'], unique=False)
    op.create_index(op.f('ix_contents_crawled_at'), 'contents', ['crawled_at'], unique=False)
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_label'), 'contents', ['label'], unique=False)
    op.create_index(op.f('ix_contents_posted_at'), 'contents', ['posted_at'], unique=False)
    op.create_index(op.f('ix_contents_source_id'), 'contents', ['source_id'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_index(op.f('ix_contents_url_id'), 'contents', ['url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_url_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_source_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_posted_at'), table_name='contents')
    op.drop_index(op.f('ix_contents_label'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_crawled_at'), table_name='contents')
    op.drop_index(op.f('ix_contents_author'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_urls_url'), table_name='urls')
    op.drop_index(op.f('ix_urls_status'), table_name='urls')
    op.drop_index(op.f('ix_urls_source_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_crawled_at'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_sources_source'), table_name='sources')
    op.drop_index(op.f('ix_sources_site'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_description'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
