"""empty message

Revision ID: f0c3799d1234
Revises: 
Create Date: 2023-08-09 20:47:51.849556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c3799d1234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polarity_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polarity', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polarity_reference_description'), 'polarity_reference', ['description'], unique=False)
    op.create_index(op.f('ix_polarity_reference_id'), 'polarity_reference', ['id'], unique=False)
    op.create_index(op.f('ix_polarity_reference_polarity'), 'polarity_reference', ['polarity'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_description'), 'project', ['description'], unique=False)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_project_project'), 'project', ['project'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('site', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_description'), 'source', ['description'], unique=False)
    op.create_index(op.f('ix_source_id'), 'source', ['id'], unique=False)
    op.create_index(op.f('ix_source_site'), 'source', ['site'], unique=True)
    op.create_index(op.f('ix_source_source'), 'source', ['source'], unique=False)
    op.create_table('aspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aspect', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aspect_aspect'), 'aspect', ['aspect'], unique=False)
    op.create_index(op.f('ix_aspect_description'), 'aspect', ['description'], unique=False)
    op.create_index(op.f('ix_aspect_id'), 'aspect', ['id'], unique=False)
    op.create_index(op.f('ix_aspect_project_id'), 'aspect', ['project_id'], unique=False)
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawled_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'failed', 'crawled'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_crawled_at'), 'url', ['crawled_at'], unique=False)
    op.create_index(op.f('ix_url_id'), 'url', ['id'], unique=False)
    op.create_index(op.f('ix_url_source_id'), 'url', ['source_id'], unique=False)
    op.create_index(op.f('ix_url_status'), 'url', ['status'], unique=False)
    op.create_index(op.f('ix_url_url'), 'url', ['url'], unique=True)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawled_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=500), nullable=True),
    sa.Column('author', sa.VARCHAR(length=500), nullable=True),
    sa.Column('posted_at', sa.VARCHAR(length=150), nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_author'), 'content', ['author'], unique=False)
    op.create_index(op.f('ix_content_crawled_at'), 'content', ['crawled_at'], unique=False)
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_index(op.f('ix_content_label'), 'content', ['label'], unique=False)
    op.create_index(op.f('ix_content_posted_at'), 'content', ['posted_at'], unique=False)
    op.create_index(op.f('ix_content_source_id'), 'content', ['source_id'], unique=False)
    op.create_index(op.f('ix_content_title'), 'content', ['title'], unique=False)
    op.create_index(op.f('ix_content_url_id'), 'content', ['url_id'], unique=False)
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.TEXT(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_content_id'), 'sentence', ['content_id'], unique=False)
    op.create_index(op.f('ix_sentence_id'), 'sentence', ['id'], unique=False)
    op.create_index(op.f('ix_sentence_source_id'), 'sentence', ['source_id'], unique=False)
    op.create_index(op.f('ix_sentence_url_id'), 'sentence', ['url_id'], unique=False)
    op.create_table('polarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('polarity_reference_id', sa.Integer(), nullable=False),
    sa.Column('aspect_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspect.id'], ),
    sa.ForeignKeyConstraint(['polarity_reference_id'], ['polarity_reference.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polarity_aspect_id'), 'polarity', ['aspect_id'], unique=False)
    op.create_index(op.f('ix_polarity_id'), 'polarity', ['id'], unique=False)
    op.create_index(op.f('ix_polarity_polarity_reference_id'), 'polarity', ['polarity_reference_id'], unique=False)
    op.create_index(op.f('ix_polarity_project_id'), 'polarity', ['project_id'], unique=False)
    op.create_index(op.f('ix_polarity_reviewer_id'), 'polarity', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_polarity_sentence_id'), 'polarity', ['sentence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_polarity_sentence_id'), table_name='polarity')
    op.drop_index(op.f('ix_polarity_reviewer_id'), table_name='polarity')
    op.drop_index(op.f('ix_polarity_project_id'), table_name='polarity')
    op.drop_index(op.f('ix_polarity_polarity_reference_id'), table_name='polarity')
    op.drop_index(op.f('ix_polarity_id'), table_name='polarity')
    op.drop_index(op.f('ix_polarity_aspect_id'), table_name='polarity')
    op.drop_table('polarity')
    op.drop_index(op.f('ix_sentence_url_id'), table_name='sentence')
    op.drop_index(op.f('ix_sentence_source_id'), table_name='sentence')
    op.drop_index(op.f('ix_sentence_id'), table_name='sentence')
    op.drop_index(op.f('ix_sentence_content_id'), table_name='sentence')
    op.drop_table('sentence')
    op.drop_index(op.f('ix_content_url_id'), table_name='content')
    op.drop_index(op.f('ix_content_title'), table_name='content')
    op.drop_index(op.f('ix_content_source_id'), table_name='content')
    op.drop_index(op.f('ix_content_posted_at'), table_name='content')
    op.drop_index(op.f('ix_content_label'), table_name='content')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_index(op.f('ix_content_crawled_at'), table_name='content')
    op.drop_index(op.f('ix_content_author'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_url_url'), table_name='url')
    op.drop_index(op.f('ix_url_status'), table_name='url')
    op.drop_index(op.f('ix_url_source_id'), table_name='url')
    op.drop_index(op.f('ix_url_id'), table_name='url')
    op.drop_index(op.f('ix_url_crawled_at'), table_name='url')
    op.drop_table('url')
    op.drop_index(op.f('ix_aspect_project_id'), table_name='aspect')
    op.drop_index(op.f('ix_aspect_id'), table_name='aspect')
    op.drop_index(op.f('ix_aspect_description'), table_name='aspect')
    op.drop_index(op.f('ix_aspect_aspect'), table_name='aspect')
    op.drop_table('aspect')
    op.drop_index(op.f('ix_source_source'), table_name='source')
    op.drop_index(op.f('ix_source_site'), table_name='source')
    op.drop_index(op.f('ix_source_id'), table_name='source')
    op.drop_index(op.f('ix_source_description'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_project_project'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_project_description'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_polarity_reference_polarity'), table_name='polarity_reference')
    op.drop_index(op.f('ix_polarity_reference_id'), table_name='polarity_reference')
    op.drop_index(op.f('ix_polarity_reference_description'), table_name='polarity_reference')
    op.drop_table('polarity_reference')
    # ### end Alembic commands ###
