# Get all urls with pagination
@status = new
@page = 1
@per_page = 2
@source_id = 1

GET http://127.0.0.1:8000/v1/urls
    ?status={{status}}
    &page={{page}}
    &per_page={{per_page}}
    &source_id={{source_id}}
